### ISSUE TITLE
Lets add README.md

### ISSUE THREAD

**Issue by ekondrashev** [ekondrashev/py2bash#3]
Lets add readme in markdown format describing 
- purpose of a project
- features supported(for, sequence, if-else, etc)
- current approach used(python ast and node visitor)
- usage
- requirements(python version - 2.7, bash version - 3.2 - check yours plz)

**Comment by ekondrashev** [comment]
@grisov please provide the PR number implementing the issue while closing the defect.

**Comment by grisov** [comment]
Fixed with #5
